### ISSUE TITLE
Figma prototype

### ISSUE THREAD

**Issue by Demezy** [InnoSWP/sustomer-susport#4]
Design interface for mobile app. (Will be used as a base for site integration indeed)

**Comment by moflotas** [comment]
First figma prototype:
https://www.figma.com/file/58maNeumAGZsOBuqRWhAbP/Sustomer-susport?node-id=0%3A1

**Comment by moflotas** [comment]
# First figma prototype:
[link](https://www.figma.com/file/58maNeumAGZsOBuqRWhAbP/Sustomer-susport?node-id=0%3A1)
